globalvar p_level;
p_level = 1;
globalvar p_health;
p_health = 20;
globalvar p_maxHealth;
p_maxHealth = 20;
globalvar p_attack;
p_attack = 5;
globalvar p_mAttack;
p_mAttack = 5;
globalvar p_defense;
p_defense = 5;
globalvar p_mDefense;
p_mDefense = 5;
globalvar p_magic;
p_magic = 20;
globalvar p_maxMagic;
p_maxMagic = 20;
globalvar p_speed;
p_speed = 10;
globalvar p_accuracy;
p_accuracy = 90;
globalvar p_dodge;
p_dodge = 5;
globalvar p_luck;
p_luck = 5;
globalvar p_exp;
p_exp = 0;
globalvar p_maxExp;
p_maxExp = 15;