/// @desc enemy_stats (health, maxHealth, attack, mAttack, defense, mDefense, speed, accuracy, dodge, luck)
/// @arg health
/// @arg maxHealth
/// @arg attack
/// @arg mAttack
/// @arg defense
/// @arg mDefense
/// @arg speed
/// @arg accuracy
/// @arg dodge
/// @arg luck
e_health = argument0;
e_maxHealth = argument1;
e_attack = argument2;
e_mAttack = argument3;
e_defense = argument4;
e_mDefense = argument5;
e_speed = argument6;
e_accuracy = argument7;
e_dodge = argument8;
e_luck = argument9;
e_exp = argument10;